services:
  - type: web
    name: currency-converter
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    autoDeploy: true
    envVars:
      - key: EXCHANGE_API_KEY
        sync: false

